version: '3'
services:
  tensorflow:
    build: .
    container_name: tensorflow-gpu
    volumes:
      - ./notebooks:/tf/notebooks
      - ./data:/tf/data
      - "C:/Users/k5906/Desktop/Kaushal-Learn/100-days-Of-DL:/tf/100-days-Of-DL"
    ports:
      - "8888:8888"  # For JupyterLab
      - "6006:6006"  # For TensorBoard
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''